payload:
  - DOMAIN-SUFFIX,cdninstagram.com
  - DOMAIN-SUFFIX,instagram.com
  - DOMAIN-SUFFIX,accountkit.com
  - DOMAIN-SUFFIX,f8.com
  - DOMAIN-SUFFIX,facebookmail.com
  - DOMAIN-SUFFIX,fb.com
  - DOMAIN-SUFFIX,fb.me
  - DOMAIN-SUFFIX,fb.watch
  - DOMAIN-SUFFIX,fbaddins.com
  - DOMAIN-SUFFIX,fbcdn.net
  - DOMAIN-SUFFIX,fbsbx.com
  - DOMAIN-SUFFIX,fbworkmail.com
  - DOMAIN-SUFFIX,m.me
  - DOMAIN-SUFFIX,messenger.com
  - DOMAIN-SUFFIX,oculus.com
  - DOMAIN-SUFFIX,oculuscdn.com
  - DOMAIN-SUFFIX,readyatdawn.com
  - DOMAIN-SUFFIX,rocksdb.org
  - DOMAIN-SUFFIX,whatsapp.com
  - DOMAIN-SUFFIX,whatsapp.net
  - DOMAIN-KEYWORD,.facebook.