name: AdRules

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */24 * * *

jobs:
  Update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]

    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: yarn install, update
        run: |
          yarn install
          yarn update-adrules
        
      - name: Merge and Rules and remove duplicates
        run: |
          awk 'FNR==1{print ""}{print}' Ruleset/AdRules/*.list > Ruleset/AdRules/Merge.txt
          awk '!seen[$0]++' Ruleset/AdRules/Merge.txt > Ruleset/AdRules/Merge.list
          rm -rf Ruleset/AdRules/Merge.txt
          rm -rf Ruleset/AdRules/Merge.list
          
      - name: commit
        run: | 
         git config --local user.name "github-actions[bot]"
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add .
         git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
             
