name: Update ASN 

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * Mon,Fri"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Run Python
        run: |
          python Script/ChinaASN.py
          python Script/ChinaIP.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update 
