name: Update ASN&IP

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Run Python
        run: |
          python Script/ChinaASN.py
          python Script/ChinaIP.py
      - name: commit
        run: | 
         git config --local user.name "iEwha"
         git config --local user.email "81971510+iEwha@users.noreply.github.com"
         git add .
         git commit -m "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
