name: Update GeoIPs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 0
jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Get GeoIP
      run: |
        cd $GITHUB_WORKSPACE/Provider/GeoIP
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-only-cn-private.mmdb
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-asn.mmdb
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
        curl -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat

    - name: commit
      run: | 
         git config --local user.name "iEwha"
         git config --local user.email "81971510+iEwha@users.noreply.github.com"
         git add .
         git commit -m "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: master
